name: Back End projet actions

on:
  push:
    branches: [ master,develop,lab,front,back]
  pull_request:
    branches: [ master,develop,lab,front,back]

jobs:

  deployBack:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: ${{ secrets.SSH_KEY_NAME  }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          path: ./backend
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: install and refresh server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/${{secrets.DEPLOY_USER }}/backend/backendreact
            chmod 777 release.sh && ./release.sh
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
